name: byop_demo                       # ← choose any environment name
channels:
  - defaults
  - conda-forge                  # community‑maintained packages
  - pytorch                       # for official PyTorch/CUDA builds

dependencies:
  # 1) Core Python version
  - python=3.12.8

  # 2) Conda‑installable packages
  - pip                           # so we can pip-install the rest
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - flask
  - h5py
  - pillow
  - protobuf
  - nltk
  - grpcio
  - pyyaml
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - cudatoolkit=11.8             # matches your GPU driver/PyTorch build

  # 3) Pure‑Python packages via pip
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - blinker==1.9.0
      - boltons==23.0.0
      # - brotli-python==1.0.9
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cryptography==43.0.3
      - flatbuffers==24.12.23
      - fmt==9.1.0
      - fonttools==4.55.3
      - gast==0.6.0
      - google-pasta==0.2.0
      - huggingface-hub==0.27.1
      - keras==3.8.0
      - kiwisolver==1.4.8
      - markdown==3.7
      - markdown-it-py==3.0.0
      - networkx==3.2.1
      - opt-einsum==3.4.0
      - packaging==24.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.5.2
      - tensorboard==2.17.1
      - tensorflow==2.17.1
      - tensorflow-intel==2.17.1
      - tf-keras==2.18.0
      - tokenizers==0.21.0
      - transformers==4.47.1
      - tqdm==4.67.1
